"""add_job_views

Revision ID: bdddfb613ea9
Revises: 876269aee09b
Create Date: 2026-08-12 15:27:19.580511
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bdddfb613ea9'
down_revision: Union[str, None] = '876269aee09b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('visitor_key', sa.String(length=64), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'visitor_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_views')
    # ### end Alembic commands ###
